const  menuCarList = [
    {
        title:'运营管理',
        key:'/operations',
        children:[
            {
                title:'订单管理',
                key:'/operations/order',
                btnList:['查看','确认用车','车辆送达','取消用车','强制结束订单','调账','订单详情']
            },
            {
                title:'身份审核',
                key:'/operations/verify',
                btnList:['查看','查看详情','审核']
            },
            {
                title:'客服中心',
                key:'/operations/customer_service',
                children:[
                    {
                        title:'用户反馈',
                        key:'/feedback',
                        btnList:['查看','跟进','导出']
                    }
                ]
            },
            {
                title:'退押金管理',
                key:'/operations/returnDeposit',
                btnList:['查看','审核']
            }
        ]
    },
    {
        title:'城市管理',
        key:'/cityManagement',
        children:[
            {
                title:'服务区管理',
                key:'/cityManagement/service_area_car',
                btnList:['查看','创建服务区','编辑服务区']
            },
            {
                title:'禁停区管理',
                key:'/cityManagement/no_parking_car',
                btnList:['查看','创建禁停区','编辑停车区','查看禁停区']
            }
        ]
    },
    {
        title:'车辆运维管理',
        key:'/maintenance',
        children:[
            {   
                title:'车辆监控',
                key:'/maintenance/monitor',
                children:[
                    {
                        title:'按车辆监控',
                        key:'/maintenance/monitor_bike',
                        btnList:['查看']
                    }
                ]
            }
        ]
    },
    {
        title:'财务管理',
        key:'/finance',
        children:[
            {
                title:'退款管理',
                key:'/finance/refund',
                btnList:['查看','退款申请','退款申请审核','退款完成确认','退回修改','退款详情']
            },
            {   
                title:'对账管理',
                key:'/finance/reconciliation',
                children:[
                    {
                        title:'用户账户',
                        key:'/finance/reconciliation/user_account',
                        btnList:['查看','导出']
                    },
                    {
                        title:'订单',
                        key:'/finance/reconciliation/order',
                        btnList:['查看','导出']
                    },
                    {
                        title:'第三方',
                        key:'/finance/reconciliation/third_party',
                        btnList:['查看','导出']
                    }
                ]
            }
        ]
    }
];
export default menuCarList;